export const ReviewsData =
  [
    {
      id: 2,
      title: 'Saaho Review',
      name: 'Saaho',
      urlToImage: '/images/saaho.jpg',
      image: '/images/saaho.jpg',
      rating: '2.5/5',
      cast: 'Prabhas, Shraddha Kapoor, Jackie Shroff, Neil Nitin Mukesh, Vennela Kishore, Murli Sharma, Arun Vijay, Prakash Belavadi, Evelyn Sharma, Supreeth, Lal, Chunky Pandey, Mandira Bedi, Mahesh Manjrekar, Tinu Anand',
      music: 'Ghibran',
      producer: 'Vamsi and Pramod',
      banner: 'UV Creations',
      writter: '',
      director: 'Sujeeth',
      released: 'August 30, 2019',
      storyintro: 'An union minister gets kidnapped by a mafia gang that run from Waaji city (fictionalized). An undercover cop Ashok Chakravarathy (Prabhas) comes into the scene. In Mumbai, some robberies happened.',
      storydetails: 'Ashok Chakravarthy and crime branch Officer Amrutha Nair (Shraddha Kapoor) on their mission to find out the person behind the robberies. They zero on a guy named Armani (Neil Nithin Mukhesh).',
      storyconclusion: 'On other hand, Roy (Jackie Shroff), the mafia don of Waaji city is assassinated. His son who has been raised in a secret place will now take his position but before that he has to bring a black box from Mumbai which was hidden in a bank. Who really is Ashok Chakravarthy and how does he involve in all this tangle is the rest of the drama.',
      heroperformance:"To come out from the royal warrior look of ‘Baahubali’ and ‘Baahubali 2’ and present himself as modern-day action star is not that easy. Prabhas has chosen a role that suits well to his image and body language. But sadly, he is not in his elements here, he seems out of place in most sequences though he has excelled in action episodes.",
      heroineperformance: 'Shraddha Kapoor is seen in a role that has enough length and importance. Hers is not glamour doll character, story gets changed with her role and she has done justice to it. Neil Nithin Mukesh is good.',
      othersperformance: 'Vennela Kishore’s comedy doesn’t work at all. The film has scores of actors as antagonists but all of them have added more confusion to the story. Only Mandira Bedi and Chunky Pandey get better roles. Jacqueline’s item song is catchy and enticing.',
      technicaldetail1: 'Money can be seen in every frame. The film absolutely boasts the best production and technical values. Since this is a lavish action film, more emphasis is given to action choreography, cinematography and production design, which all are of international standards.',
      technicaldetail2: 'The two action episodes compassed by Kenny Bates will definitely stand out. Actions stunts are never seen like before on an Indian screen. But the marathon action episodes are boring. Cinematography by Madhi is excellent.',
      finalnote: 'All in all, the film is a huge let-down.',
      author: 'Editorial Chief',
      urlname: 'saaho-review',
      category: 'entertainment/reviews',
      date: 'Sep 09, 2019'
    },{
      id: 1,
      title: 'Evaru Review',
      name: 'Evaru',
      urlToImage: '/images/evaru.png',
      image: '/images/evarumain.png',
      rating: '3/5',
      cast: 'Adivi Sesh, Regina Cassandra, Naveen Chandra, Murali Sharma, Pavithra Lokesh, Nihal and others',
      music: 'Sricharan Pakala',
      producer: 'Pearl V. Potluri, Param V. Potluri, Kavin Anne',
      banner: 'PVP Cinema',
      writter: '',
      director: 'Venkat Ramji',
      released: 'August 15, 2019',
      storyintro: 'Sameera (Regina) is accused of murdering her lover, with whom she is having a relationship outside marriage as her husband is gay.',
      storydetails: 'Sameera came to a Coonoor resort in Tamilnadu with her lover Ashok. Her friend bribes a police officer Vikram Vasudev (Adivi Sesh) to help Sameera to build a defense case before she appears in the court of law.',
      storyconclusion: 'He asks her account, why did she murder her own lover and what really has happened.',
      heroperformance:"The film completely belongs to Regina. She is terrific in the role of Sameera. She has not only done bold scenes with ease but also pulled off the act of deceit with aplomb. Evaru is her show.",
      heroineperformance: 'Adivi Sesh has also done quite well in a role that required him to showcase two variations. He has shown maturity in acting.',
      othersperformance: 'Naveen Chandra in an all-important role is good. Pavitra Lokesh and Murali Sharma have done in their usual manner.',
      technicaldetail1: 'The film has rich visuals. Cinematography and production values are top class. Editing and background music are huge assets. The film has no songs. Dialogues are effective.',
      technicaldetail2: '',
      finalnote: 'Well Done!',
      author: 'Editorial Chief',
      urlname: 'evaru-review',
      category: 'entertainment/reviews',
      date: 'Sep 10, 2019'
    }
  ]
